/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M18
 * Generated at: 2017-12-04 03:42:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class add_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/add.css\" type=\"text/css\">\r\n");
      out.write("<script type=\"text/javascript\" src=\"JS/jquery-1.4.1.min.js\"></script>\r\n");
      out.write("<body>\r\n");
      out.write("\t<h2>学生信息添加</h2>\r\n");
      out.write("\t姓名：\r\n");
      out.write("\t<input type=\"text\" name=\"name\" id=\"name\">\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br> 账号：\r\n");
      out.write("\t<input type=\"text\" name=\"num\" id=\"num\">\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br> 密码 ：\r\n");
      out.write("\t<input type=\"text\" name=\"password\" id=\"password\">\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br> 年龄：\r\n");
      out.write("\t<input type=\"text\" name=\"age\" id=\"age\">\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br> 性别：\r\n");
      out.write("\t<input type=\"radio\" name=\"sex\" checked=\"checked\" value=\"男\">男\r\n");
      out.write("\t<input type=\"radio\" name=\"sex\" value=\"女\">女\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br> 爱好：\r\n");
      out.write("\t<input type=\"checkbox\" name=\"hobby\" value=\"音乐\">音乐\r\n");
      out.write("\t<input type=\"checkbox\" name=\"hobby\" value=\"阅读\">阅读\r\n");
      out.write("\t<input type=\"checkbox\" name=\"hobby\" value=\"运动\">运动\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br> 生源地：\r\n");
      out.write("\t<select name=\"sheng\" id=\"sheng\">\r\n");
      out.write("\t\t<option value=\"江苏\">江苏\r\n");
      out.write("\t\t<option value=\"安徽\">安徽\r\n");
      out.write("\t\t<option value=\"湖南\">湖南\r\n");
      out.write("\t</select>\r\n");
      out.write("\t<select name=\"shi\" id=\"shi\">\r\n");
      out.write("\t\t<option value=\"常州市\">常州市\r\n");
      out.write("\t\t<option value=\"合肥市\">合肥市\r\n");
      out.write("\t\t<option value=\"长沙市\">长沙市\r\n");
      out.write("\t</select>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<input type=\"button\" id=\"b1\" value=\"提交\">\r\n");
      out.write("\t<input type=\"reset\" id=\"b2\" value=\"重置\">\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(function() {\r\n");
      out.write("\t\t$(\"#b1\").click(function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar name = $(\"#name\").val();\r\n");
      out.write("\t\t\tvar password = $(\"#password\").val();\r\n");
      out.write("\t\t\tvar num = $(\"#num\").val();\r\n");
      out.write("\t\t\tvar age = $(\"#age\").val();\r\n");
      out.write("\t\t\tvar sex = [];\r\n");
      out.write("\t\t\t$('input[name=sex]:checked').each(function() {\r\n");
      out.write("\t\t\t\tsex.push($(this).val());\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tvar hobbies = [];\r\n");
      out.write("\t\t\t$('input[name=hobby]:checked').each(function() {\r\n");
      out.write("\t\t\t\thobbies.push($(this).val());\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\tvar sheng = $(\"#sheng\").val();\r\n");
      out.write("\t\t\tvar shi = $(\"#shi\").val();\r\n");
      out.write("\t\t\tvar aj = $.ajax({\r\n");
      out.write("\t\t\t\ttype : 'POST',\r\n");
      out.write("\t\t\t\turl : 'AddServlet',\r\n");
      out.write("\t\t\t\ttraditional : true,\r\n");
      out.write("\t\t\t\tdata : {\r\n");
      out.write("\t\t\t\t\tname : num,\r\n");
      out.write("\t\t\t\t\tpassword : password,\r\n");
      out.write("\t\t\t\t\tnum : num,\r\n");
      out.write("\t\t\t\t\tage : age,\r\n");
      out.write("\t\t\t\t\tsex : sex[0],\r\n");
      out.write("\t\t\t\t\thobby : hobbies,\r\n");
      out.write("\t\t\t\t\tsheng : sheng,\r\n");
      out.write("\t\t\t\t\tshi : shi\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t\tif (data == 1) {\r\n");
      out.write("\t\t\t\t\t\talert(\"添加成功！\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif (data == 2) {\r\n");
      out.write("\t\t\t\t\t\talert(\"添加失败！\");\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\terror : function(data) {\r\n");
      out.write("\t\t\t\t\talert(\"系统内部错误！请联系管理员！\");\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
