/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M18
 * Generated at: 2018-01-11 02:30:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.BufferedReader;
import java.io.InputStreamReader;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.io.BufferedReader");
    _jspx_imports_classes.add("java.io.InputStreamReader");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<title>会员登录</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.min.css\" type=\"text/css\" />\r\n");
      out.write("<script src=\"js/jquery-1.11.3.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<!-- 引入自定义css文件 style.css -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\" type=\"text/css\" />\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tmargin-top: 20px;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".carousel-inner .item img {\r\n");
      out.write("\twidth: 100%;\r\n");
      out.write("\theight: 300px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container .row div {\r\n");
      out.write("\t/* position:relative;\r\n");
      out.write("\t\t\t\t float:left; */\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("font {\r\n");
      out.write("\tcolor: #666;\r\n");
      out.write("\tfont-size: 22px;\r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("\tpadding-right: 17px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction sendcode(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar usid = document.getElementById(\"username\").value;\r\n");
      out.write("\t\tif(usid!=\"\" && usid!=null){\r\n");
      out.write("\t\t\tlocation.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sendEmail?usid=\"\r\n");
      out.write("\t\t\t\t+ usid;\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\talert(\"请输入用户名!\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t$(function(){  \r\n");
      out.write("        $(\"#getCode\").removeAttr(\"disabled\"); \r\n");
      out.write("        //发送验证码  \r\n");
      out.write("        $(\"#getCode\").click(function(){   \r\n");
      out.write("            $.ajax({  \r\n");
      out.write("                url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sendEmail\",  \r\n");
      out.write("                data:{  \r\n");
      out.write("                    \"us_id\":$(\"#username\").val()\r\n");
      out.write("                },  \r\n");
      out.write("                type:\"post\",  \r\n");
      out.write("                async:false,  \r\n");
      out.write("                dataType:\"text\",  \r\n");
      out.write("                success : function(data) {  \r\n");
      out.write("                    if(1 == data){  \r\n");
      out.write("                        alert(\"验证码发送成功，收到后请输入验证码\");  \r\n");
      out.write("                        time(this);  \r\n");
      out.write("                    } else {  \r\n");
      out.write("                        alert(\"验证码发送失败\");  \r\n");
      out.write("                    }  \r\n");
      out.write("                },  \r\n");
      out.write("                error : function() {  \r\n");
      out.write("                    alert(\"error\");  \r\n");
      out.write("                }  \r\n");
      out.write("            });  \r\n");
      out.write("        });  \r\n");
      out.write("        //验证  \r\n");
      out.write("        $(\"#validate\").click(function(){      \r\n");
      out.write("            $.ajax({  \r\n");
      out.write("                url:\"code\",  \r\n");
      out.write("                data:{  \r\n");
      out.write("                    \"code\":$(\"#code\").val()  \r\n");
      out.write("                },  \r\n");
      out.write("                type:\"post\",  \r\n");
      out.write("                async:false,  \r\n");
      out.write("                dataType:\"text\",  \r\n");
      out.write("                success : function(data) {  \r\n");
      out.write("                    if(data=='true'){  \r\n");
      out.write("                        alert(\"恭喜您，验证成功\");  \r\n");
      out.write("                    } else {  \r\n");
      out.write("                        alert(\"验证失败\");  \r\n");
      out.write("                    }  \r\n");
      out.write("                },  \r\n");
      out.write("                error : function() {  \r\n");
      out.write("                    alert(\"error\");  \r\n");
      out.write("                }  \r\n");
      out.write("            });  \r\n");
      out.write("        });  \r\n");
      out.write("    })  \r\n");
      out.write("      \r\n");
      out.write("    //验证码倒计时  \r\n");
      out.write("    var wait = 60;  \r\n");
      out.write("    function time(obj) {  \r\n");
      out.write("        if(wait==0) {  \r\n");
      out.write("            $(\"#getCode\").removeAttr(\"disabled\");  \r\n");
      out.write("            $(\"#getCode\").val(\"获取验证码\");  \r\n");
      out.write("            wait = 60;  \r\n");
      out.write("        }else {  \r\n");
      out.write("            $(\"#getCode\").attr(\"disabled\",\"true\");  \r\n");
      out.write("            $(\"#getCode\").val(wait+\"秒后重试\");  \r\n");
      out.write("            wait--;  \r\n");
      out.write("            setTimeout(function() {     //倒计时方法  \r\n");
      out.write("                time(obj);  \r\n");
      out.write("            },1000);    //间隔为1s  \r\n");
      out.write("        }  \r\n");
      out.write("    }  \r\n");
      out.write("</script>  \r\n");
      out.write("\t\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 引入header.jsp -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container\"\r\n");
      out.write("\t\tstyle=\"width: 100%; height: 460px; background: #FF2C4C url('images/loginbg.jpg') no-repeat;\">\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t<!--<img src=\"./image/login.jpg\" width=\"500\" height=\"330\" alt=\"会员登录\" title=\"会员登录\">-->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-md-5\">\r\n");
      out.write("\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\tstyle=\"width: 440px; border: 1px solid #E7E7E7; padding: 20px 0 20px 30px; border-radius: 5px; margin-top: 60px; background: #fff;\">\r\n");
      out.write("\t\t\t\t\t<font>会员登录</font>USER LOGIN\r\n");
      out.write("\t\t\t\t\t<div>&nbsp;</div>\r\n");
      out.write("\t\t\t\t\t<form class=\"form-horizontal\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/userlogin\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"username\" class=\"col-sm-2 control-label\">用户名</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"username\" name = \"userid\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"请输入用户名\"> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputPassword3\" class=\"col-sm-2 control-label\">密码</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-6\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"inputPassword3\" name=\"userpassword\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"请输入密码\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label for=\"inputPassword3\" class=\"col-sm-2 control-label\">验证码</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"inputPassword3\" name=\"usercode\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tplaceholder=\"请输入验证码\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <img src=\"./image/captcha.jhtml\" /> -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<!-- <a href=\"#\" onclick=\"sendcode1() placeholder=\"4位验证码\">发送验证码 </a>   -->\r\n");
      out.write("\t\t\t\t\t\t\t\t<input id=\"getCode\" type=\"button\" value=\"发送验证码\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"checkbox\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<label> <input type=\"checkbox\" name=\"autoLogin\" value=\"autoLogin\"> 自动登录\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <label> <input\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\ttype=\"checkbox\"> 记住用户名\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</label>\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-offset-2 col-sm-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"submit\" width=\"100\" value=\"登录\" name=\"submit\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"background: url('./images/login.gif') no-repeat scroll 0 0 rgba(0, 0, 0, 0); height: 35px; width: 100px; color: white;\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- 引入footer.jsp -->\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
